name: Docker Build

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: evergene/certy:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: meeDamian/sync-readme@1.0.6
      with:
        user: ${{ secrets.DOCKERHUB_USERNAME }}
        pass: ${{ secrets.DOCKERHUB_TOKEN }}
        readme: ./.github/docker/README.md
        description: true
        slug: evergene/certy
